camunda.bpm.operate:
  elasticsearch:
    clusterName: elasticsearch
    host: elasticsearch
    port: 9300
    dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  zeebe:
    brokerContactPoint: zeebe:26500
    worker: operate
  zeebeElasticsearch:
    clusterName: elasticsearch
    host: elasticsearch
    port: 9300
    prefix: zeebe-record
logging:
  level:
    ROOT: INFO
    org.camunda.operate: DEBUG
